/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldTest {
    @Test public void testHelloWorld() {
        String output = HelloWorld.hello("from Rust!");
        assertNotNull("output expected", output);
    }
}
